# Generated by Django 4.2.29 on 2026-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodmarkerreading',
            name='marker_type',
            field=models.CharField(blank=True, choices=[('hba1c', 'HbA1c'), ('glucose_fasting', 'Glucose (Fasting)'), ('glucose_pp', 'Glucose (Post Prandial)'), ('cholesterol_total', 'Total Cholesterol'), ('hdl', 'HDL Cholesterol'), ('ldl', 'LDL Cholesterol'), ('triglycerides', 'Triglycerides'), ('hemoglobin', 'Hemoglobin'), ('vitamin_d', 'Vitamin D'), ('vitamin_b12', 'Vitamin B12')], max_length=50, null=True),
        ),
    ]
