export const API_ENDPOINTS = {
    auth: {
        currentUser: "auth/user/",
        passwordReset: "auth/password/reset/",
        passwordResetConfirm: "auth/password/reset/confirm/",
    },
    organizations: {
        settings: (tenantId: string) => `organizations/${tenantId}/settings/`,
    },
    clients: {
        list: "clients/clients/",
        detail: (id: string) => `clients/clients/${id}/`,
        activate: (id: string) => `clients/clients/${id}/activate/`,
        deactivate: (id: string) => `clients/clients/${id}/deactivate/`,
    },
    meal: {
        foodItems: "meal/food-items/",
        foodItemDetail: (id: string) => `meal/food-items/${id}/`,
        plans: "meal/plans/",
        planDetail: (id: string) => `meal/plans/${id}/`,
        assignments: "meal/assignments/",
        assignmentDetail: (id: string) => `meal/assignments/${id}/`,
        plannedMeals: "meal/planned-meals/",
        plannedMealDetail: (id: string) => `meal/planned-meals/${id}/`,
        generateDietPlanPdf: "meal/generate-pdf/",
        downloadDietPlanPdf: "meal/download-pdf/",
    },
    features: {
        list: "features/",
    },
    packages: {
        list: "packages/",
        detail: (id: string) => `packages/${id}/`,
    },
    coupons: {
        list: "coupons/",
        detail: (id: string) => `coupons/${id}/`,
        usages: (id: string) => `coupons/${id}/usages/`,
    },
    orders: {
        list: "orders/orders/",
        detail: (id: string) => `orders/orders/${id}/`,
    },
    payments: {
        checkoutIntentDetail: (id: string) => `payments/checkout-intents/${id}/`,
        adminCashPayments: "payments/admin-cash-payments/",
        adminManualPayments: "payments/admin-manual-payments/",
        adminCheckoutIntents: "payments/admin-checkout-intents/",
        adminPaymentLinks: "payments/admin-payment-links/",
        paymentLinkSummary: (token: string) => `payments/payment-links/${token}/`,
        paymentLinkCheckout: (token: string) => `payments/payment-links/${token}/checkout/`,
    },
    communications: {
        messageTemplates: "communications/message-templates/",
        messageTemplateDetail: (id: string) => `communications/message-templates/${id}/`,
        testMessageTemplate: (id: string) => `communications/message-templates/${id}/test-send/`,
        emailLogs: "communications/email-logs/",
        whatsappLogs: "communications/whatsapp-logs/",
    },
    engagement: {
        followups: "engagement/followups/",
        followupDetail: (id: string) => `engagement/followups/${id}/`,
        suggestedTargets: "engagement/followups/suggested-targets/",
    },
    reports: {
        bloodReports: "reports/blood-reports/",
        bloodReportDetail: (id: string) => `reports/blood-reports/${id}/`,
    },
    progress: {
        checkins: "progress/daily-checkins/",
        checkinDetail: (id: string) => `progress/daily-checkins/${id}/`,
        checkinLogs: "progress/daily-checkins-logs/",
        checkinLogDetail: (id: string | number) => `progress/daily-checkins-logs/${id}/`,
        weeklyMeasurements: "progress/weekly-measurements/",
        weeklyMeasurementDetail: (id: string) => `progress/weekly-measurements/${id}/`,
    },
    subscriptions: {
        memberships: "subscriptions/memberships/",
        membershipDetail: (id: string) => `subscriptions/memberships/${id}/`,
        features: "subscriptions/features/",
        featureDetail: (id: string) => `subscriptions/features/${id}/`,
    },
    workout: {
        plans: "workout/plans/",
        planDetail: (id: string) => `workout/plans/${id}/`,
        assignments: "workout/assignments/",
        assignmentDetail: (id: string) => `workout/assignments/${id}/`,
        assignmentDownloadPdf: (id: string) => `workout/assignments/${id}/download-pdf/`,
        assignmentSendPdf: (id: string) => `workout/assignments/${id}/send-pdf/`,
        days: "workout/days/",
        dayDetail: (id: string | number) => `workout/days/${id}/`,
        exercises: "workout/exercises/",
        exerciseDetail: (id: string) => `workout/exercises/${id}/`,
        muscleGroups: "workout/muscle-groups/",
        muscleGroupDetail: (id: string | number) => `workout/muscle-groups/${id}/`,
        muscles: "workout/muscles/",
        muscleDetail: (id: string | number) => `workout/muscles/${id}/`,
        workoutExercises: "workout/workout-exercises/",
        workoutExerciseDetail: (id: string | number) => `workout/workout-exercises/${id}/`,
    },
} as const;
