export const API_ENDPOINTS = {
    auth: {
        passwordReset: "auth/password/reset/",
        passwordResetConfirm: "auth/password/reset/confirm/",
    },
    clients: {
        list: "clients/clients/",
        detail: (id: string) => `clients/clients/${id}/`,
        activate: (id: string) => `clients/clients/${id}/activate/`,
        deactivate: (id: string) => `clients/clients/${id}/deactivate/`,
    },
    meal: {
        generateDietPlanPdf: "meal/generate-pdf/",
        downloadDietPlanPdf: "meal/download-pdf/",
    },
    features: {
        list: "features/",
    },
    packages: {
        list: "packages/",
        detail: (id: string) => `packages/${id}/`,
    },
    coupons: {
        list: "coupons/",
        detail: (id: string) => `coupons/${id}/`,
    },
    orders: {
        list: "orders/orders/",
        detail: (id: string) => `orders/orders/${id}/`,
    },
    payments: {
        checkoutIntentDetail: (id: string) => `payments/checkout-intents/${id}/`,
        adminCashPayments: "payments/admin-cash-payments/",
        adminManualPayments: "payments/admin-manual-payments/",
        adminCheckoutIntents: "payments/admin-checkout-intents/",
        adminPaymentLinks: "payments/admin-payment-links/",
        paymentLinkSummary: (token: string) => `payments/payment-links/${token}/`,
        paymentLinkCheckout: (token: string) => `payments/payment-links/${token}/checkout/`,
    },
    communications: {
        emailLogs: "communications/email-logs/",
    },
    subscriptions: {
        memberships: "subscriptions/memberships/",
        membershipDetail: (id: string) => `subscriptions/memberships/${id}/`,
        features: "subscriptions/features/",
        featureDetail: (id: string) => `subscriptions/features/${id}/`,
    },
    workout: {
        plans: "workout/plans/",
        planDetail: (id: string) => `workout/plans/${id}/`,
        assignments: "workout/assignments/",
        assignmentDetail: (id: string) => `workout/assignments/${id}/`,
        assignmentDownloadPdf: (id: string) => `workout/assignments/${id}/download-pdf/`,
        assignmentSendPdf: (id: string) => `workout/assignments/${id}/send-pdf/`,
        days: "workout/days/",
        dayDetail: (id: string | number) => `workout/days/${id}/`,
        exercises: "workout/exercises/",
        exerciseDetail: (id: string) => `workout/exercises/${id}/`,
        muscleGroups: "workout/muscle-groups/",
        muscleGroupDetail: (id: string | number) => `workout/muscle-groups/${id}/`,
        muscles: "workout/muscles/",
        muscleDetail: (id: string | number) => `workout/muscles/${id}/`,
        workoutExercises: "workout/workout-exercises/",
        workoutExerciseDetail: (id: string | number) => `workout/workout-exercises/${id}/`,
        sessions: "workout/sessions/",
        sessionDetail: (id: string) => `workout/sessions/${id}/`,
        logs: "workout/logs/",
        logDetail: (id: string) => `workout/logs/${id}/`,
        sets: "workout/sets/",
        setDetail: (id: string) => `workout/sets/${id}/`,
    },
} as const;
