# Generated by Django 6.0.3 on 2026-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_client_type_product_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-yearly', 'Half-yearly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], default='monthly', max_length=20),
        ),
    ]
