# Generated by Django 4.2.29 on 2026-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_date_of_joining_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
