# Generated by Django 4.2.29 on 2026-04-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_staffprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
