# Generated by Django 4.2.29 on 2026-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes for this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_link_token',
            field=models.UUIDField(blank=True, help_text='Token for payment link checkout', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Pay by Card'), ('payment_link', 'Payment Link')], default='card', max_length=20),
        ),
    ]
