# Generated by Django 6.0.4 on 2026-06-14 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_rename_clients_cli_assigne_3277d4_idx_clients_cli_assigne_8aa79b_idx_and_more'),
        ('tenants', '0004_remove_organizationmember_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('equipment_required', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.musclegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='workout.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='workout.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.musclegroup')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('name', models.CharField(max_length=100)),
                ('day_number', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('sets', models.IntegerField()),
                ('reps', models.CharField(max_length=50)),
                ('rest', models.IntegerField(help_text='rest in minutes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise_type', models.IntegerField(choices=[(1, 'Body Weight'), (2, 'Pin Loaded Machine'), (3, 'Free Weight')], default=3)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutday')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_sets', models.IntegerField(blank=True, null=True)),
                ('planned_reps', models.IntegerField(blank=True, null=True)),
                ('planned_weight', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='workout.exercise')),
                ('plan_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.workoutexercise')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Workout Log',
                'verbose_name_plural': 'Workout Logs',
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('rest_sec', models.IntegerField()),
                ('is_pr', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout.workoutlog')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('workout', 'Workout'), ('diet', 'Diet'), ('hybrid', 'Hybrid (Workout + Diet)')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_weeks', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plan_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan_assignments', to='clients.clientprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_plan_assignments', to='workout.workoutplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Workout Plan Assignment',
                'verbose_name_plural': 'Workout Plan Assignments',
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='plan_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_day', to='workout.workoutplanassignment'),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='clients.clientprofile')),
                ('plan_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workout.workoutplanassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('workout_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.workoutday')),
            ],
            options={
                'verbose_name': 'Workout Session',
                'verbose_name_plural': 'Workout Sessions',
            },
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workout.workoutsession'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['tenant', 'muscle_group'], name='workout_exe_tenant__4b0cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['tenant', 'plan_type', 'is_active'], name='workout_wor_tenant__02db73_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplanassignment',
            index=models.Index(fields=['tenant', 'client', 'status'], name='workout_wor_tenant__dd1f2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('plan_assignment', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['tenant', 'client', 'session_date'], name='workout_wor_tenant__b3477a_idx'),
        ),
    ]
