# Generated by Django 6.0.4 on 2026-05-03 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('report_file', models.FileField(upload_to='blood_reports/%Y/%m/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_reports', to='clients.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Blood Report',
                'verbose_name_plural': 'Blood Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marker_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='reports.bloodreport')),
            ],
            options={
                'verbose_name': 'Blood Marker',
                'verbose_name_plural': 'Blood Markers',
            },
        ),
        migrations.AddIndex(
            model_name='bloodreport',
            index=models.Index(fields=['tenant', 'client', 'report_date'], name='reports_blo_tenant__8cccee_idx'),
        ),
    ]
