# Generated by Django 4.2.29 on 2026-04-04 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_weeks', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('fluid_intake', models.FloatField(blank=True, help_text='Litres', null=True)),
                ('hunger_level', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('craving_level', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('cardio_mins', models.IntegerField(blank=True, null=True)),
                ('session_completed', models.BooleanField(default=False)),
                ('motivation', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('performance', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('muscle_soreness', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('energy_levels', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('stress_levels', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('stool_frequency', models.IntegerField(blank=True, null=True)),
                ('stool_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('gi_distress', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_duration', models.FloatField(blank=True, help_text='Hours', null=True)),
                ('sleep_quality', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='checkins.checkinplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['week_number', 'day_of_week'],
                'unique_together': {('plan', 'week_number', 'day_of_week')},
            },
        ),
    ]
