# Generated by Django 6.0.4 on 2026-05-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('week_number', models.IntegerField()),
                ('date', models.DateField()),
                ('fluid_intake', models.FloatField(help_text='In Litres')),
                ('hunger_level', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('craving_level', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('off_plan_meal', models.BooleanField(default=False)),
                ('off_plan_meal_details', models.TextField(blank=True, help_text='Describe the off-plan meal if applicable', null=True)),
                ('steps', models.IntegerField(help_text='In Steps')),
                ('cardio', models.BooleanField(default=False)),
                ('cardio_duration', models.IntegerField(help_text='In Minutes')),
                ('strength_training', models.BooleanField(default=False)),
                ('strength_training_details', models.TextField(blank=True, help_text='Describe the strength training if applicable', null=True)),
                ('motivation', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('performance', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('muscle_soreness', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True)),
                ('energy_levels', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True)),
                ('stress_levels', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True)),
                ('stool_frequency', models.IntegerField(blank=True, null=True)),
                ('stool_quality', models.CharField(choices=[('loose', 'Loose'), ('regular', 'Regular'), ('hard', 'Hard')], max_length=10)),
                ('gi_distress', models.CharField(blank=True, help_text='BLOATING, CONSTIPATION, DIARRHEA, ETC', max_length=100, null=True)),
                ('sleep_duration', models.FloatField(blank=True, help_text='Hours', null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True)),
                ('notes', models.TextField(blank=True, help_text="MENTION ANY ACCOMPLISHMENT YOU'RE PROUD AND/OR HURDLES YOU MIGHT HAVE FACED TODAY & WOULD LIKE TO SHARE", null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='checkins.checkin')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['plan', 'date'], name='checkins_ch_plan_id_08e0af_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'date'), name='unique_daily_log_per_plan_per_date')],
            },
        ),
    ]
