# Generated by Django 6.0.4 on 2026-05-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_remove_checkinlog_deleted_at'),
        ('clients', '0003_clientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='clients.clientprofile'),
        ),
    ]
