# Generated by Django 6.0.4 on 2026-05-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_alter_checkin_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='deleted_at',
        ),
    ]
