# Generated by Django 6.0.4 on 2026-05-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exercise',
            new_name='planning_ex_tenant__047af6_idx',
            old_name='planning_ex_tenant__59cf80_idx',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.musclegroup'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='plan_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_day', to='planning.workoutplanassignment'),
        ),
    ]
