# Generated by Django 6.0.4 on 2026-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_rename_planning_ex_tenant__59cf80_idx_planning_ex_tenant__047af6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_required',
            field=models.BooleanField(default=False),
        ),
    ]
