# Generated by Django 6.0.4 on 2026-05-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_and_more'),
        ('planning', '0003_remove_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workoutplanassignment',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='workoutplanassignment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan_assignments', to='clients.clientprofile'),
        ),
    ]
