# Generated by Django 6.0.4 on 2026-05-03 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMeasurement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arm_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arm_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calf_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calf_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glutes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thighs_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thighs_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-measured_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('photo_type', models.CharField(choices=[('front', 'Front'), ('left_side', 'Left Side'), ('right_side', 'Right Side'), ('back', 'Back')], default='front', max_length=10)),
                ('image', models.ImageField(upload_to='measurements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='measurement.weeklymeasurement')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklymeasurement',
            index=models.Index(fields=['tenant', 'measured_at'], name='measurement_tenant__aefdbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementphoto',
            constraint=models.UniqueConstraint(fields=('measurement', 'photo_type'), name='unique_measurement_photo_per_type'),
        ),
    ]
