# Generated by Django 6.0.4 on 2026-05-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_and_more'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementphoto',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='weeklymeasurement',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='weeklymeasurement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='clients.clientprofile'),
        ),
    ]
