# Generated by Django 6.0.4 on 2026-05-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='deleted_at',
        ),
    ]
