# Generated by Django 6.0.4 on 2026-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_organization_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
