# Generated by Django 6.0.4 on 2026-05-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_role_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='deleted_at',
        ),
    ]
