# Generated by Codex on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_organizationmember_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(default='#EF4444', max_length=7),
        ),
    ]
