# Generated by Django 6.0.4 on 2026-05-03 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '__first__'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount'), ('fixed_price', 'Fixed Price Override'), ('free_shipping', 'Free Shipping')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fixed_price_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Used for FIXED_PRICE overrides', max_digits=10, null=True)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage discounts', max_digits=10, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('subscription', 'Subscription'), ('referral', 'Referral'), ('affiliate', 'Affiliate'), ('flash', 'Flash Sale'), ('early_bird', 'Early Bird'), ('upgrade', 'Upgrade')], default='general', max_length=20)),
                ('user_segment', models.CharField(choices=[('all', 'All Users'), ('first_time', 'First-time Users'), ('returning', 'Returning Customers'), ('vip', 'VIP / Premium'), ('referral', 'Referral Recipient')], default='all', max_length=20)),
                ('is_auto_applied', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('referrer_reward_value', models.DecimalField(blank=True, decimal_places=2, help_text='Reward given to referrer upon use', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('first_time_users_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buy_x_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('get_y_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_extension_days', models.PositiveIntegerField(blank=True, null=True)),
                ('applies_to_upgrade', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_packages', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='packages.package')),
                ('applicable_plans', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='packages.packageplan')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Coupon Rule',
                'verbose_name_plural': 'Coupon Rules',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['tenant', 'code'], name='coupons_cou_tenant__17df0a_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='coupons_cou_valid_f_cf442c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_cou_is_acti_a50634_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_auto_applied'], name='coupons_cou_is_auto_e906d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('code', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='coupons_cou_coupon__830da4_idx'),
        ),
    ]
