# Generated by Django 6.0.4 on 2026-05-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_couponusage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='deleted_at',
        ),
    ]
