# Generated by Django 6.0.4 on 2026-05-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='deleted_at',
        ),
    ]
