# Generated by Django 6.0.4 on 2026-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='storage_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
