# Generated by Django 6.0.4 on 2026-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staffprofile_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
