# Generated by Django 6.0.4 on 2026-05-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='health_and_fitness_data',
        ),
    ]
