# Generated by Django 6.0.3 on 2026-04-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='assigned_coach',
            new_name='assigned_trainer',
        ),
    ]
