# Generated by Django 6.0.4 on 2026-05-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_alter_checkin_client'),
        ('clients', '0003_clientprofile_and_more'),
        ('meal', '0002_remove_dietlog_deleted_at_remove_dietplan_deleted_at_and_more'),
        ('measurement', '0002_remove_measurementphoto_deleted_at_and_more'),
        ('orders', '0003_remove_order_deleted_at_alter_order_client'),
        ('payments', '0002_remove_payment_deleted_at_and_more'),
        ('planning', '0004_remove_exercise_deleted_at_and_more'),
        ('reports', '0002_remove_bloodreport_deleted_at_and_more'),
        ('subscriptions', '0003_remove_feature_deleted_at_and_more'),
        ('tracking', '0002_remove_setlog_deleted_at_and_more'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Client',
    #     ),
    # ]
