# Generated by Django 6.0.4 on 2026-05-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_delete_client'),
        ('staff', '0002_remove_staffprofile_deleted_at'),
        ('tenants', '0004_remove_organizationmember_deleted_at_and_more'),
    ]

    operations = []
