# Generated by Codex on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientprofile_assigned_trainer_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS clients_clientprofile (
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                deleted_at timestamp with time zone NULL,
                dob date NULL,
                sex varchar(1) NULL,
                profile_picture varchar(100) NULL,
                date_of_joining date NULL,
                phone varchar(20) NULL,
                id uuid NOT NULL PRIMARY KEY,
                status varchar(20) NOT NULL,
                referral_source varchar(255) NULL,
                joined_at timestamp with time zone NOT NULL,
                activated_at timestamp with time zone NULL,
                goal varchar(20) NULL,
                assigned_trainer_id uuid NULL,
                org_client_id uuid NOT NULL UNIQUE,
                tenant_id uuid NOT NULL
            );

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'clients_clientprofile_assigned_trainer_id_fk'
                ) THEN
                    ALTER TABLE clients_clientprofile
                    ADD CONSTRAINT clients_clientprofile_assigned_trainer_id_fk
                    FOREIGN KEY (assigned_trainer_id)
                    REFERENCES staff_staffprofile (id)
                    ON DELETE SET NULL;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'clients_clientprofile_org_client_id_fk'
                ) THEN
                    ALTER TABLE clients_clientprofile
                    ADD CONSTRAINT clients_clientprofile_org_client_id_fk
                    FOREIGN KEY (org_client_id)
                    REFERENCES tenants_organizationmember (id)
                    ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'clients_clientprofile_tenant_id_fk'
                ) THEN
                    ALTER TABLE clients_clientprofile
                    ADD CONSTRAINT clients_clientprofile_tenant_id_fk
                    FOREIGN KEY (tenant_id)
                    REFERENCES tenants_organization (id)
                    ON DELETE CASCADE;
                END IF;
            END $$;

            CREATE INDEX IF NOT EXISTS clients_cli_assigne_3277d4_idx
                ON clients_clientprofile (assigned_trainer_id);

            CREATE INDEX IF NOT EXISTS clients_cli_status_ce0d15_idx
                ON clients_clientprofile (status);

            CREATE INDEX IF NOT EXISTS clients_cli_tenant__11a885_idx
                ON clients_clientprofile (tenant_id, status);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
