# Generated by Django 6.0.4 on 2026-05-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_recreate_clientprofile_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientprofile',
            new_name='clients_cli_assigne_8aa79b_idx',
            old_name='clients_cli_assigne_3277d4_idx',
        ),
        migrations.RenameIndex(
            model_name='clientprofile',
            new_name='clients_cli_status_74a7e3_idx',
            old_name='clients_cli_status_ce0d15_idx',
        ),
        migrations.RenameIndex(
            model_name='clientprofile',
            new_name='clients_cli_tenant__bcf1be_idx',
            old_name='clients_cli_tenant__11a885_idx',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='deleted_at',
        ),
    ]
