# Generated by Django 6.0.4 on 2026-05-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.clientprofile'),
        ),
    ]
