# Generated by Codex on 2026-06-08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_clientprofile_and_more"),
        ("orders", "0001_initial"),
        ("payments", "0002_remove_payment_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="webhook_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="CheckoutIntent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="When this record was created")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, help_text="Last time this record was updated")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(choices=[("user_checkout", "User Checkout"), ("admin_payment_link", "Admin Payment Link")], max_length=30)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("paid", "Paid"), ("failed", "Failed"), ("expired", "Expired")], default="pending", max_length=20)),
                ("gateway", models.CharField(max_length=50)),
                ("provider_order_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("gateway_payment_id", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("payment_link_token", models.UUIDField(blank=True, null=True, unique=True)),
                ("order_snapshot", models.JSONField(blank=True, default=dict)),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="checkout_intents", to="clients.clientprofile")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_checkout_intents", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="checkout_intents", to="orders.order")),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.organization")),
            ],
            options={
                "verbose_name": "Checkout Intent",
                "verbose_name_plural": "Checkout Intents",
                "indexes": [
                    models.Index(fields=["tenant", "source", "status"], name="payments_ch_tenant__fd6985_idx"),
                    models.Index(fields=["tenant", "client", "status"], name="payments_ch_tenant__a43d9e_idx"),
                    models.Index(fields=["provider_order_id"], name="payments_ch_provider_907db9_idx"),
                ],
            },
        ),
    ]
