# Generated by Django 6.0.4 on 2026-06-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_checkoutintent_and_gateway_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkoutintent',
            new_name='payments_ch_tenant__555719_idx',
            old_name='payments_ch_tenant__fd6985_idx',
        ),
        migrations.RenameIndex(
            model_name='checkoutintent',
            new_name='payments_ch_tenant__19ff21_idx',
            old_name='payments_ch_tenant__a43d9e_idx',
        ),
        migrations.RenameIndex(
            model_name='checkoutintent',
            new_name='payments_ch_provide_65598c_idx',
            old_name='payments_ch_provider_907db9_idx',
        ),
    ]
