# Generated by Django 6.0.4 on 2026-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_package_deleted_at_and_more'),
        ('tenants', '0004_remove_organizationmember_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='packageplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'package', 'name'), name='unique_package_plan_per_package'),
        ),
    ]
