# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packageplan_unique_package_plan_per_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_freezes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='package',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='plans',
                to='packages.package',
            ),
        ),
    ]
