# Generated by Codex on 2026-05-23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_max_freezes_packageplan_related_name'),
        ('subscriptions', '0006_use_catalog_package_plans'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='PackageFeature',
                    fields=[
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_features', to='subscriptions.feature')),
                        ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_features', to='packages.package')),
                        ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                    ],
                    options={
                        'verbose_name': 'Package Feature',
                        'verbose_name_plural': 'Package Features',
                        'db_table': 'subscriptions_packagefeature',
                    },
                ),
                migrations.AddIndex(
                    model_name='packagefeature',
                    index=models.Index(fields=['tenant', 'package'], name='subscriptio_tenant__7ab2a6_idx'),
                ),
                migrations.AddIndex(
                    model_name='packagefeature',
                    index=models.Index(fields=['tenant', 'feature'], name='subscriptio_tenant__02cc53_idx'),
                ),
                migrations.AddConstraint(
                    model_name='packagefeature',
                    constraint=models.UniqueConstraint(fields=('package', 'feature'), name='unique_package_feature'),
                ),
            ],
        ),
    ]
