# Generated by Django 6.0.4 on 2026-05-03 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('base_end_date', models.DateField()),
                ('extended_end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.client')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='orders.order')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='subscriptions.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
        migrations.CreateModel(
            name='MembershipFreeze',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='subscriptions.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Membership Freeze',
                'verbose_name_plural': 'Membership Freezes',
            },
        ),
        migrations.CreateModel(
            name='MembershipPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_freezes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Membership Package',
                'verbose_name_plural': 'Membership Packages',
            },
        ),
        migrations.CreateModel(
            name='MembershipChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=10)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='subscriptions.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('from_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subscriptions.membershippackage')),
                ('to_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subscriptions.membershippackage')),
            ],
            options={
                'verbose_name': 'Membership Change',
                'verbose_name_plural': 'Membership Changes',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='subscriptions.membershippackage'),
        ),
        migrations.CreateModel(
            name='MembershipSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='Snapshot of the package details at the time of purchase')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='subscriptions.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Membership Snapshot',
                'verbose_name_plural': 'Membership Snapshots',
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_features', to='subscriptions.feature')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_features', to='subscriptions.membershippackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Package Feature',
                'verbose_name_plural': 'Package Features',
            },
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['tenant', 'name'], name='subscriptio_tenant__28aad5_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipfreeze',
            index=models.Index(fields=['tenant', 'membership'], name='subscriptio_tenant__f11760_idx'),
        ),
        migrations.AddIndex(
            model_name='membershippackage',
            index=models.Index(fields=['tenant', 'tier', 'is_active'], name='subscriptio_tenant__e876e8_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipchange',
            index=models.Index(fields=['tenant', 'membership'], name='subscriptio_tenant__384d56_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant', 'client', 'status'], name='subscriptio_tenant__3c0f75_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['extended_end_date'], name='subscriptio_extende_9334dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagefeature',
            constraint=models.UniqueConstraint(fields=('package', 'feature'), name='unique_package_feature'),
        ),
    ]
