# Generated by Django 6.0.4 on 2026-05-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_and_more'),
        ('subscriptions', '0002_alter_feature_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='membershipchange',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='membershipfreeze',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='membershippackage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='membershipsnapshot',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='packagefeature',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='membership',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.clientprofile'),
        ),
    ]
