# Generated by Codex on 2026-05-19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_feature_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='packagefeature',
            index=models.Index(fields=['tenant', 'package'], name='subscriptio_tenant__c6c5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='packagefeature',
            index=models.Index(fields=['tenant', 'feature'], name='subscriptio_tenant__54962f_idx'),
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_type', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], default='one_time', max_length=20)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
            },
        ),
        migrations.CreateModel(
            name='AddonFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_features', to='subscriptions.addon')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_features', to='subscriptions.feature')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Addon Feature',
                'verbose_name_plural': 'Addon Features',
            },
        ),
        migrations.CreateModel(
            name='MembershipAddon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_addons', to='subscriptions.addon')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='subscriptions.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Membership Addon',
                'verbose_name_plural': 'Membership Addons',
            },
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['tenant', 'is_active'], name='subscriptio_tenant__1e9ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['tenant', 'name'], name='subscriptio_tenant__9e7f01_idx'),
        ),
        migrations.AddConstraint(
            model_name='addon',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_addon_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='addonfeature',
            index=models.Index(fields=['tenant', 'addon'], name='subscriptio_tenant__c46c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='addonfeature',
            index=models.Index(fields=['tenant', 'feature'], name='subscriptio_tenant__6641f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='addonfeature',
            constraint=models.UniqueConstraint(fields=('addon', 'feature'), name='unique_addon_feature'),
        ),
        migrations.AddIndex(
            model_name='membershipaddon',
            index=models.Index(fields=['tenant', 'membership', 'status'], name='subscriptio_tenant__e0545f_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipaddon',
            index=models.Index(fields=['tenant', 'addon'], name='subscriptio_tenant__85a57d_idx'),
        ),
    ]
