# Generated by Django 6.0.4 on 2026-05-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_packagefeature_indexes_and_addons'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='addon',
            new_name='subscriptio_tenant__c69741_idx',
            old_name='subscriptio_tenant__1e9ef7_idx',
        ),
        migrations.RenameIndex(
            model_name='addon',
            new_name='subscriptio_tenant__5739f9_idx',
            old_name='subscriptio_tenant__9e7f01_idx',
        ),
        migrations.RenameIndex(
            model_name='addonfeature',
            new_name='subscriptio_tenant__510c86_idx',
            old_name='subscriptio_tenant__c46c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='addonfeature',
            new_name='subscriptio_tenant__857bd7_idx',
            old_name='subscriptio_tenant__6641f2_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipaddon',
            new_name='subscriptio_tenant__3f7fd5_idx',
            old_name='subscriptio_tenant__e0545f_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipaddon',
            new_name='subscriptio_tenant__c8b0b7_idx',
            old_name='subscriptio_tenant__85a57d_idx',
        ),
        migrations.RenameIndex(
            model_name='packagefeature',
            new_name='subscriptio_tenant__7ab2a6_idx',
            old_name='subscriptio_tenant__c6c5f8_idx',
        ),
        migrations.RenameIndex(
            model_name='packagefeature',
            new_name='subscriptio_tenant__02cc53_idx',
            old_name='subscriptio_tenant__54962f_idx',
        ),
    ]
