# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


def migrate_membership_packages_to_catalog(apps, schema_editor):
    MembershipPackage = apps.get_model('subscriptions', 'MembershipPackage')
    Membership = apps.get_model('subscriptions', 'Membership')
    MembershipChange = apps.get_model('subscriptions', 'MembershipChange')
    Package = apps.get_model('packages', 'Package')
    PackagePlan = apps.get_model('packages', 'PackagePlan')

    legacy_plan_by_package_id = {}

    for legacy_package in MembershipPackage.objects.all():
        package, created = Package.objects.get_or_create(
            id=legacy_package.id,
            defaults={
                'tenant_id': legacy_package.tenant_id,
                'name': legacy_package.name,
                'description': legacy_package.description,
                'max_freezes': legacy_package.max_freezes,
                'is_active': legacy_package.is_active,
            },
        )
        if not created:
            package.max_freezes = legacy_package.max_freezes
            package.is_active = legacy_package.is_active
            package.save(update_fields=['max_freezes', 'is_active'])

        plan, _ = PackagePlan.objects.get_or_create(
            tenant_id=legacy_package.tenant_id,
            package=package,
            name=legacy_package.name,
            defaults={
                'price': legacy_package.price,
                'duration_in_days': legacy_package.duration_days,
                'is_active': legacy_package.is_active,
            },
        )
        legacy_plan_by_package_id[legacy_package.id] = plan.id

    memberships = Membership.objects.exclude(package_id__isnull=True)
    for membership in memberships.iterator():
        plan_id = legacy_plan_by_package_id.get(membership.package_id)
        if plan_id:
            membership.plan_id = plan_id
            membership.save(update_fields=['plan'])

    changes = MembershipChange.objects.all()
    for change in changes.iterator():
        from_plan_id = legacy_plan_by_package_id.get(change.from_package_id)
        to_plan_id = legacy_plan_by_package_id.get(change.to_package_id)
        if from_plan_id and to_plan_id:
            change.from_plan_id = from_plan_id
            change.to_plan_id = to_plan_id
            change.save(update_fields=['from_plan', 'to_plan'])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('packages', '0004_package_max_freezes_packageplan_related_name'),
        ('subscriptions', '0005_rename_subscriptio_tenant__1e9ef7_idx_subscriptio_tenant__c69741_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memberships',
                to='packages.packageplan',
            ),
        ),
        migrations.AddField(
            model_name='membershipchange',
            name='from_plan',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='packages.packageplan',
            ),
        ),
        migrations.AddField(
            model_name='membershipchange',
            name='to_plan',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='packages.packageplan',
            ),
        ),
        migrations.RunPython(migrate_membership_packages_to_catalog, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='packagefeature',
            name='unique_package_feature',
        ),
        migrations.RemoveIndex(
            model_name='membershippackage',
            name='subscriptio_tenant__e876e8_idx',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='package',
        ),
        migrations.RemoveField(
            model_name='membershipchange',
            name='from_package',
        ),
        migrations.RemoveField(
            model_name='membershipchange',
            name='to_package',
        ),
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memberships',
                to='packages.packageplan',
            ),
        ),
        migrations.AlterField(
            model_name='membershipchange',
            name='from_plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='packages.packageplan',
            ),
        ),
        migrations.AlterField(
            model_name='membershipchange',
            name='to_plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='packages.packageplan',
            ),
        ),
        migrations.AlterField(
            model_name='packagefeature',
            name='package',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='package_features',
                to='packages.package',
            ),
        ),
        migrations.AddConstraint(
            model_name='packagefeature',
            constraint=models.UniqueConstraint(fields=('package', 'feature'), name='unique_package_feature'),
        ),
        migrations.DeleteModel(
            name='MembershipPackage',
        ),
    ]
