# Generated by Codex on 2026-05-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_move_packagefeature_from_subscriptions'),
        ('subscriptions', '0006_use_catalog_package_plans'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='PackageFeature',
                ),
            ],
        ),
    ]
