# Generated by Django 6.0.4 on 2026-06-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_paid_order_delivery_tasks'),
        ('tenants', '0004_remove_organizationmember_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membership',
            new_name='subscriptio_tenant__4af3a3_idx',
            old_name='subscriptio_tenant__c795d7_idx',
        ),
        migrations.RenameIndex(
            model_name='plandeliverytask',
            new_name='subscriptio_tenant__10561d_idx',
            old_name='subscriptio_tenant__a169f6_idx',
        ),
        migrations.RenameIndex(
            model_name='plandeliverytask',
            new_name='subscriptio_tenant__3dc1f4_idx',
            old_name='subscriptio_tenant__54370c_idx',
        ),
        migrations.RenameIndex(
            model_name='plandeliverytask',
            new_name='subscriptio_tenant__cdf618_idx',
            old_name='subscriptio_tenant__dff244_idx',
        ),
        migrations.AlterField(
            model_name='plandeliverytask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization'),
        ),
    ]
