# Generated by Django 4.2.29 on 2026-03-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('owner', 'Owner'), ('coach', 'Coach'), ('trainer', 'Trainer'), ('marketing', 'Marketing')], max_length=20, null=True),
        ),
    ]
