# Generated by Django 6.0.3 on 2026-04-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_product_billing_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
