# Generated by Django 6.0.3 on 2026-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_subscription_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
