# Generated by Django 6.0.3 on 2026-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_date_of_joining_user_referral_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('owner', 'Owner'), ('coach', 'Coach'), ('trainer', 'Trainer'), ('marketing', 'Marketing'), ('client', 'Client')], max_length=20, null=True),
        ),
    ]
