# Generated by Django 6.0.3 on 2026-04-04 17:35

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staffprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_dashboard', 'Can view the staff dashboard list')]},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=users.models.get_role_choices, help_text="User's primary role, synced from Django Groups.", max_length=50, null=True),
        ),
    ]
