# Generated by Django 6.0.4 on 2026-05-03 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('goal', models.CharField(blank=True, choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20, null=True)),
                ('calories_target', models.IntegerField(blank=True, null=True)),
                ('protein_target', models.IntegerField(blank=True, null=True)),
                ('carbs_target', models.IntegerField(blank=True, null=True)),
                ('fat_target', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to='staff.staffprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Diet Plan',
                'verbose_name_plural': 'Diet Plans',
            },
        ),
        migrations.CreateModel(
            name='DietPlanAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adjustments', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_assignments', to='clients.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meal.dietplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Diet Plan Assignment',
                'verbose_name_plural': 'Diet Plan Assignments',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'indexes': [models.Index(fields=['name'], name='meal_foodit_name_33dec8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('meal_slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner'), ('pre_workout', 'Pre Workout'), ('post_workout', 'Post Workout')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='meal.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal.meal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('meal_slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner'), ('pre_workout', 'Pre Workout'), ('post_workout', 'Post Workout')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal.dietplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Planned Meal',
                'verbose_name_plural': 'Planned Meals',
                'ordering': ['day_number', 'meal_slot'],
            },
        ),
        migrations.CreateModel(
            name='PlannedMealItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meal.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal.plannedmeal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
            ],
            options={
                'verbose_name': 'Planned Meal Item',
                'verbose_name_plural': 'Planned Meal Items',
            },
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time this record was updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('water_ml', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.organization')),
                ('plan_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_logs', to='meal.dietplanassignment')),
            ],
            options={
                'verbose_name': 'Diet Log',
                'verbose_name_plural': 'Diet Logs',
                'indexes': [models.Index(fields=['tenant', 'client', 'log_date'], name='meal_dietlo_tenant__1f7b6a_idx')],
                'unique_together': {('client', 'log_date')},
            },
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['tenant', 'client', 'log_date'], name='meal_meal_tenant__4d0d6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='plannedmeal',
            constraint=models.UniqueConstraint(fields=('plan', 'day_number', 'meal_slot'), name='unique_meal_per_slot_per_day'),
        ),
    ]
