# Generated by Django 6.0.4 on 2026-05-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientprofile_and_more'),
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='dietplanassignment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='plannedmeal',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='plannedmealitem',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='dietlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='dietplanassignment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_assignments', to='clients.clientprofile'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='clients.clientprofile'),
        ),
    ]
